spring:
  application:
    name: notification-service
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWT_JWK_SET_URI:http://localhost:9000/oauth2/jwks}

resilience4j:
  ratelimiter:
    configs:
      default:
        limit-for-period: 10
        limit-refresh-period: 1m
        timeout-duration: 0s

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      show-details: never
